# Generated by Django 3.2.8 on 2021-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('prix', models.FloatField(null=True)),
                ('dete_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
