# Generated by Django 3.2.8 on 2021-11-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nome',
            new_name='nom',
        ),
    ]
