# Generated by Django 3.2.8 on 2021-11-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_rename_nome_produit_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='dete_creation',
        ),
    ]
