# Generated by Django 3.2.8 on 2021-11-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20211117_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Tag',
            new_name='tag',
        ),
    ]
