# Generated by Django 3.2.8 on 2021-11-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_rename_tag_produit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tag',
        ),
    ]
