# Generated by Django 3.2.8 on 2021-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_remove_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='tag',
            field=models.ManyToManyField(to='produit.Tag'),
        ),
    ]
