# Generated by Django 3.2.8 on 2021-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('telephon', models.CharField(max_length=200, null=True)),
                ('dete_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
